### PR TITLE
Wrong plugin version in setup.py

### PR DESCRIPTION
**Pull request by stevendejongnl**

### CODE REVIEW

**Comment by LuckyX182** [comment]
Forgot about this, thank you very much!

**Comment by stevendejongnl** [comment]
@LuckyX182 I think the release tag needs to be reset to the last merge to rebuild the zip.

**Comment by cp2004** [comment]
Correct, since OctoPrint's software update will keep downloading the tag, rather than the master branch. Not sure if deleting the tag can be done in GitHub's UI, but it can be done from the command line with git or using an IDE that might have the feature. Otherwise a new 0.3.3 release may be required, incrementing the version again before tagging.

**Comment by LuckyX182** [comment]
I think new 0.3.3 version will be the easiest thing to do. Thanks guys.

**Pull request merged**
